package com.aymen.digitu.countriesview

/**
 * Created by mohamedaymenmejri on 04,March,2020
 */
enum class CountriesDisplayTag(val key: String) {
    EU_CALLING_CODE_DISPLAY("EU CALLING CODE DISPLAY"),
    EU_NAME_DISPLAY("EU NAME DISPLAY"),
    WORLD_EU_FIRST_CALLING_CODE_DISPLAY("WORLD EU FIRST CALLING CODE DISPLAY"),
    WORLD_EU_FIRST_NAME_DISPLAY("WORLD EU FIRST NAME DISPLAY"),
    WORLD_CALLING_CODE_DISPLAY("WORLD CALLING CODE DISPLAY"),
    WORLD_NAME_DISPLAY("WORLD NAME DISPLAY")
}
